name: CI

on:
  push:
    branches: [ main ]


jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Move war file to tomcat webapp
        run: | 
         cd build/libs
         mv lol-cloud-0.0.1-SNAPSHOT.jar ~/Desktop/tomcat/apache-tomcat-10.1.13/webapps 
